/*
  PRODUCT CATALOGUE
  To add a product: copy one complete object, paste it before the closing ],
  change the id (must be unique), text, filters and image path.
*/
window.PRODUCTS = [
  {
    id: 'royal-blue-full-voile',
    name: 'Royal Blue Full-Voile Pagri Fabric',
    category: 'Sikh Pagri Fabrics',
    occasion: ['Daily Wear', 'Religious Occasion'],
    colors: ['Royal Blue', 'Navy Blue', 'White'],
    image: 'assets/images/owner-shop.webp',
    alt: 'Royal blue fabric rolls suitable for Sikh pagri tying',
    summary: 'A refined pagri fabric option with a clean fall and rich royal-blue appearance.',
    details: 'Suitable for customers looking for a smart traditional pagri with a smooth, balanced finish. Ask the shop to confirm current fabric quality, width and shade availability.',
    material: 'Pagri fabric; exact quality and width confirmed during enquiry.',
    recommended: 'Daily wear, gurdwara visits, family functions and coordinated outfits.'
  },
  {
    id: 'navy-comfort-daily',
    name: 'Navy Comfort Daily-Wear Turban Fabric',
    category: 'Daily-Wear Turban Fabrics',
    occasion: ['Daily Wear', 'Office Wear'],
    colors: ['Navy Blue', 'Black', 'Bottle Green'],
    image: 'assets/images/original-lavender-turban.webp',
    alt: 'Navy and dark-toned fabric textures for daily turban use',
    summary: 'Comfort-focused turban cloth in practical shades for regular use.',
    details: 'Designed as an enquiry option for customers prioritising comfort, grip and easy colour coordination. Actual stock varies by shade and fabric quality.',
    material: 'Comfort-oriented turban fabric; exact composition available at the shop.',
    recommended: 'College, work, daily routines and understated traditional looks.'
  },
  {
    id: 'maroon-premium-fabric',
    name: 'Maroon Premium Occasion Pagri Fabric',
    category: 'Premium Turban Fabrics',
    occasion: ['Engagement', 'Festive Occasion'],
    colors: ['Maroon', 'Wine', 'Rust'],
    image: 'assets/images/original-red-safa-groom.webp',
    alt: 'Maroon and wine fabric rolls for premium pagri styling',
    summary: 'A deeper premium palette for engagements, celebrations and evening functions.',
    details: 'A rich-colour pagri fabric concept that can be matched against a kurta, waistcoat or sherwani reference. Send an outfit photo for closer colour guidance.',
    material: 'Premium pagri fabric; finish and weave depend on selected quality.',
    recommended: 'Engagements, festive events, receptions and coordinated family looks.'
  },
  {
    id: 'red-wedding-pagri',
    name: 'Red Wedding-Special Pagri',
    category: 'Wedding Turbans',
    occasion: ['Wedding', 'Groom Ceremony'],
    colors: ['Red', 'Maroon', 'Pink'],
    image: 'assets/images/original-peach-wedding-pagri.webp',
    alt: 'Original peach wedding pagri with gold stripes displayed on a mannequin',
    summary: 'A statement wedding pagri direction with decorative detailing and matching support.',
    details: 'Created for groom styling enquiries where the pagri must coordinate with sherwani embroidery, stole, jewellery and wedding décor. Ready and fabric-based options can be discussed.',
    material: 'Wedding pagri or pagri fabric with optional decorative styling.',
    recommended: 'Wedding ceremony, groom portrait session and main baraat look.'
  },
  {
    id: 'rajasthani-ceremonial-safa',
    name: 'Rajasthani Ceremonial Safa',
    category: 'Rajasthani Safas',
    occasion: ['Wedding', 'Baraat', 'Cultural Event'],
    colors: ['Cream', 'Red', 'Mustard'],
    image: 'assets/images/original-red-safa-groom.webp',
    alt: 'Original groom portrait wearing a red ceremonial safa and navy suit',
    summary: 'A ceremonial safa concept for grooms, family members and festive groups.',
    details: 'Available for individual and group enquiries. Share the outfit colours, quantity and function date so matching and availability can be checked.',
    material: 'Ready safa or safa fabric depending on requirement.',
    recommended: 'Baraat, destination weddings, cultural functions and family coordination.'
  },
  {
    id: 'cream-kurta-pajama-fabric',
    name: 'Cream Kurta-Pajama Fabric',
    category: 'Kurta-Pajama Fabrics',
    occasion: ['Daily Wear', 'Family Function', 'Festive Occasion'],
    colors: ['Cream', 'White', 'Peach'],
    image: 'assets/images/original-wedding-groom-ceremony.webp',
    alt: 'Original wedding groom wearing an ivory sherwani and matching pagri',
    summary: 'A versatile light-toned fabric direction for traditional tailoring and pagri matching.',
    details: 'Choose the fabric feel and shade according to season, tailoring preference and occasion. The shop can help coordinate a pagri colour with the final outfit.',
    material: 'Kurta-pajama fabric; exact blend and quality confirmed in store.',
    recommended: 'Anand Karaj functions, family gatherings, festive wear and daily traditional clothing.'
  },
  {
    id: 'formal-coat-pant-fabric',
    name: 'Formal Coat-Pant Fabric Selection',
    category: 'Coat-Pant Fabrics',
    occasion: ['Reception', 'Formal Occasion'],
    colors: ['Navy Blue', 'Black', 'Charcoal'],
    image: 'assets/images/original-red-safa-groom.webp',
    alt: 'Original formal groom portrait in a navy suit and ceremonial red safa',
    summary: 'Formal suiting choices for a polished reception or occasion look.',
    details: 'Discuss colour, season and tailoring requirements before selecting the cloth. Matching turban shades can be suggested for a coordinated Punjabi formal look.',
    material: 'Suiting fabric; exact weave, weight and composition vary by selection.',
    recommended: 'Reception, engagement, formal dinner and occasion tailoring.'
  },
  {
    id: 'royal-blazer-fabric',
    name: 'Royal Blazer & Suiting Fabric',
    category: 'Blazer Fabrics',
    occasion: ['Reception', 'Winter Function'],
    colors: ['Royal Blue', 'Navy Blue', 'Wine'],
    image: 'assets/images/original-red-safa-groom.webp',
    alt: 'Original navy suit and red ceremonial safa photographed inside the shop',
    summary: 'Rich blazer and suiting shades selected to work with traditional accessories.',
    details: 'A fabric-selection enquiry for customers planning a blazer, bandhgala or coordinated winter function look. Ask for current options before visiting.',
    material: 'Blazer and suiting fabrics in multiple seasonal qualities.',
    recommended: 'Reception, winter wedding, formal function and coordinated pagri styling.'
  },
  {
    id: 'antique-gold-kalgi',
    name: 'Antique-Gold Groom Kalgi',
    category: 'Kalgis',
    occasion: ['Wedding', 'Groom Ceremony'],
    colors: ['Gold', 'Cream', 'Red'],
    image: 'assets/images/original-peach-wedding-pagri.webp',
    alt: 'Original peach wedding pagri with gold-striped decorative detailing',
    summary: 'A regal kalgi direction designed to enhance the groom’s wedding pagri.',
    details: 'Kalgi designs can be selected separately or matched with a pagri and sehra. Share close-up images of sherwani work or jewellery for better coordination.',
    material: 'Decorative groom accessory; design and finish depend on availability.',
    recommended: 'Main wedding ceremony, groom portrait and royal pagri styling.'
  },
  {
    id: 'cream-floral-sehra',
    name: 'Cream Floral Wedding Sehra',
    category: 'Sehras',
    occasion: ['Wedding', 'Groom Ceremony'],
    colors: ['Cream', 'White', 'Soft Gold'],
    image: 'assets/images/original-wedding-groom-ceremony.webp',
    alt: 'Original wedding ceremony portrait featuring an ivory groom pagri',
    summary: 'A soft ceremonial sehra concept for cream, ivory and gold groom outfits.',
    details: 'Sehra availability and construction may vary. Enquire with the event date and pagri colour so a coordinated option can be recommended.',
    material: 'Decorative sehra; floral, beaded or coordinated styles may be available.',
    recommended: 'Wedding ceremony and traditional groom entry.'
  },
  {
    id: 'groom-accessory-combination',
    name: 'Groom Accessory Combination',
    category: 'Groom Accessories',
    occasion: ['Wedding', 'Engagement', 'Reception'],
    colors: ['Gold', 'Cream', 'Maroon'],
    image: 'assets/images/original-wedding-groom-ceremony.webp',
    alt: 'Original groom ceremony photograph showing layered pearl accessories',
    summary: 'A coordinated combination of pagri accents and groom styling accessories.',
    details: 'Build a combination around the sherwani, pagri colour and preferred level of ornamentation. Individual accessory availability can be confirmed on WhatsApp.',
    material: 'Accessory selection may include kalgi, malas, brooches and related items.',
    recommended: 'Complete groom styling for wedding, engagement or reception.'
  },
  {
    id: 'complete-wedding-kit',
    name: 'Complete Royal Wedding Kit',
    category: 'Wedding Kits',
    occasion: ['Wedding', 'Groom Ceremony'],
    colors: ['Custom Match', 'Cream', 'Maroon'],
    image: 'assets/images/wedding-accessory-kits.webp',
    alt: 'Wedding pagri and accessory gift kits arranged for display',
    summary: 'A complete non-priced package concept for coordinated groom essentials.',
    details: 'The kit can be discussed around pagri, kalgi, sehra, matching accessories and family safa requirements. Contents are finalised according to the selected look.',
    material: 'Custom combination of wedding pagri and accessories.',
    recommended: 'Customers wanting one coordinated enquiry for the full wedding look.'
  },
  {
    id: 'custom-colour-matching',
    name: 'Custom Outfit Colour Matching',
    category: 'Custom Colour Matching',
    occasion: ['Wedding', 'Family Function', 'Any Occasion'],
    colors: ['Custom Match', 'Royal Blue', 'Maroon', 'Cream'],
    image: 'assets/images/owner-shop.webp',
    alt: 'Owner presenting a bright fabric roll for in-store colour matching',
    summary: 'Personal guidance to match pagri fabric and accessories with an outfit reference.',
    details: 'Send a clear photo in natural light or visit with the outfit. Similar shades can be shortlisted, but final colour confirmation is best done in person.',
    material: 'Consultation service for fabrics, pagris and accessories.',
    recommended: 'Sherwani, kurta-pajama, suit, family outfits and wedding themes.'
  },
  {
    id: 'family-baraat-safa-order',
    name: 'Family & Baraat Safa Order',
    category: 'Wedding Kits',
    occasion: ['Baraat', 'Wedding', 'Group Order'],
    colors: ['Custom Match', 'Royal Blue', 'Mustard', 'Maroon'],
    image: 'assets/images/original-red-safa-groom.webp',
    alt: 'Original groom portrait wearing a ceremonial red safa inside the shop',
    summary: 'Coordinated safa or pagri enquiries for family members and baraat groups.',
    details: 'Provide the expected quantity, colour reference, function date and preferred style. Availability and preparation requirements will be discussed before confirmation.',
    material: 'Group turban or safa requirement; style depends on event needs.',
    recommended: 'Baraat groups, close family, wedding teams and cultural events.'
  },
  {
    id: 'white-ceremonial-turban',
    name: 'Ivory & White Ceremonial Turban',
    category: 'Premium Turban Fabrics',
    occasion: ['Wedding', 'Religious Occasion', 'Formal Occasion'],
    colors: ['White', 'Cream', 'Soft Gold'],
    image: 'assets/images/original-wedding-groom-ceremony.webp',
    alt: 'Original wedding groom wearing an ivory pagri and embroidered sherwani',
    summary: 'An elegant ivory-and-gold direction for minimal, formal and ceremonial styling.',
    details: 'Suitable for outfits that need a refined light shade rather than a high-contrast colour. Ask about plain and decorative options.',
    material: 'Premium turban fabric or ready ceremonial turban depending on stock.',
    recommended: 'Wedding functions, religious ceremonies and refined formal looks.'
  },
  {
    id: 'bottle-green-pagri',
    name: 'Bottle Green Pagri Fabric',
    category: 'Sikh Pagri Fabrics',
    occasion: ['Daily Wear', 'Festive Occasion'],
    colors: ['Bottle Green', 'Emerald Green'],
    image: 'assets/images/original-lavender-turban.webp',
    alt: 'Original close-up portrait showing a neatly tied lavender Sikh turban',
    summary: 'A confident green pagri shade for daily or festive coordination.',
    details: 'Green shades can change noticeably under indoor and outdoor light. Send a natural-light outfit photo or compare the fabric in store before finalising.',
    material: 'Pagri fabric in green shades; quality depends on current collection.',
    recommended: 'Daily wear, festive functions and contrast styling with light outfits.'
  }
];
